# values.yaml for Cilium Helm Chart with Traffic Encryption

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - 172.1.0.0/16

encryption:
  enabled: true
  type: wireguard # Use 'ipsec' if you prefer IPsec encryption


operator:
  replicas: 1 # Number of Cilium Operator replicas

cluster:
  id: 1 # Unique cluster ID for Cilium
  name: my-cluster # Name of your Kubernetes cluster

ipv4:
  enabled: true # Enable IPv4 support for the cluster

nodeEncryption: true # Enable encryption for node-to-node traffic
