podSecurityPolicy:
  enabled: true

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

securityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

serviceAccount:
  create: true
  name: longhorn-service-account

rbac:
  create: true


enableNetworkPolicy: true

enablePSP: true
