global:
  name: consul

  tls:
    enabled: true
    logLevel: warn
    enableAutoEncrypt: true
    verify: true
    metrics:
      enabled: true
      enableAgentMetrics: true
      agentMetricsRetentionTime: "10m"

connectInject:
  enabled: true
  enableTLS: true
  cni:
    enabled: true
    logLevel: info
    cniBinDir: "/opt/cni/bin"
    cniNetDir: "/etc/cni/net.d"
    resources:
      requests:
        memory: "75Mi"
        cpu: "75m"
      limits:
        memory: "300Mi"
        cpu: "100m"
  
dns:
  enabled: true
  enableRedirection: true
  type: ClusterIP

meshGateway:
  enabled: true
  replicas: 1
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "500Mi"
      cpu: "200m"
  tls:
    enableAutoEncrypt: true

acl:
  enabled: true
  defaultPolicy: deny
  tokens:
    # Use Kubernetes secrets for ACL tokens
    master:
      secretName: consul-master-token
      secretKey: master-token
    agent:
      secretName: consul-agent-token
      secretKey: agent-token
