apiVersion: v1
kind: Service
metadata:
  name: boundary-service
spec:
  type: NodePort
  selector:
    app: boundary
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 32000
  - protocol: TCP
    port: 9201
    targetPort: 9201
    nodePort: 32001
  - protocol: TCP
    port: 9202
    targetPort: 9202
    nodePort: 32002
