apiVersion: v1
kind: Service
metadata:
  name: boundary-service
spec:
  selector:
    app: boundary
  ports:
  - protocol: TCP
    port: 9200
    targetPort: 9200
  - protocol: TCP
    port: 9201
    targetPort: 9201
  - protocol: TCP
    port: 9202
    targetPort: 9202
  type: ClusterIP
