apiVersion: v1
kind: Pod
metadata:
  name: boundary-init
spec:
  hostNetwork: true
  containers:
    - name: boundary
      image: hashicorp/boundary:latest
      command:
        - /bin/sh
        - -c
        - |
          boundary database init -config /boundary/config.hcl > /boundary/output.log 2>&1
      env:
        - name: BOUNDARY_POSTGRES_URL
          value: "postgresql://postgres:postgres@postgres-service.boundary.svc.k3s.littleobi.com:5432/postgres?sslmode=disable"
      volumeMounts:
        - name: output-volume
          mountPath: /boundary/output.log
          subPath: output.log
  volumes:
    - name: output-volume
      emptyDir: {}
