apiVersion: v1
kind: Pod
metadata:
  name: boundary-init
spec:
  containers:
    - name: boundary
      image: hashicorp/boundary:latest
      env:
        - name: BOUNDARY_POSTGRES_URL
          value: "postgresql://postgres:postgres@postgress.boundary.svc.k3s.littleobi.com:5432/postgres?sslmode=disable"

