injector:
   enabled: false
server:
   dataStorage:
     enabled: true
     storageClass: longhorn
     size: 5Gi
   auditStorage:
     enabled: true
     storageClass: longhorn
     size: 5Gi
   ha:
    enabled: true
    replicas: 2
    raft:
      enabled: true
      setNodeId: true

      config: |
        ui = true
        cluster_name = "vault-integrated-storage"
        listener "tcp" {
          tls_disable = 1
          address = "vault.vault.svc.k3s.littleobi.com:8200"
          cluster_address = "vault.vault.svc.k3s.littleobi.com:8201"
        }

        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "https://vault-0.vault.pod.k3s.littleobi.com:8200"
          }
          retry_join {
            leader_api_addr = "https://vault-1.vault.pod.k3s.littleobi.com:8200"
          }
        }
