
server:
   affinity: null
   dataStorage:
     enabled: true
     storageClass: longhorn
     size: 5Gi
   auditStorage:
     enabled: true
     storageClass: longhorn
     size: 5Gi
   ha:
    enabled: true
    replicas: 1 
    raft:
      enabled: true