server:
   dataStorage:
     enabled: true
     storageClass: longhorn
     size: 5Gi
   auditStorage:
     enabled: true
     storageClass: longhorn
     size: 5Gi
   ha:
    enabled: true
    replicas: 2
    raft:
      enabled: true
