server:
   dataStorage:
     enabled: true
     storageClass: longhorn
     size: 5Gi
   auditStorage:
     enabled: true
     storageClass: longhorn
     size: 5Gi
   ha:
    enabled: true
    replicas: 2
    raft:
      enabled: true

      config: |
        listener "tcp" {
          tls_disable = 1
          address = "vault.vault.svc.k3s.littleobi.com:8200"
          cluster_address = "vault.vault.svc.k3s.littleobi.com:8201"
        }

        storage "raft" {
          path = "/vault/data"
          retry_join {
            leader_api_addr = "http://vault-0.vault-internal:8200"
          }
        
          retry_join {
            leader_api_addr = "http://vault-0.vault-internal:8200"
          }
         }