apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "boundary:8200" # Replace with the appropriate service name and port
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--no-autoupdate", "run", "--token", "$(TOKEN)"]
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token
              key: token
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          fsGroup: 2000
      serviceAccountName: cloudflared-sa
      securityContext:
        fsGroup: 2000

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared-sa
