apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "boundary-service" # Replace with the appropriate service name and port
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args: ["tunnel", "--no-autoupdate", "run", "--token", "$(TOKEN)"]
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token
              key: token
          
        

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared-sa
