apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
data:
  token: "eyJhIjoiM2E4N2YwMzQxNGQ0ZjQ1MDMwOGE5ZDMzNzZmNWFiNWMiLCJ0IjoiMGEzYzdmZjMtZjZkMy00ZmU0LWEyMzktYmUyOTEzY2U0NmY2IiwicyI6Ik9EUmhOemxpWXpVdE9Ea3dNUzAwTWpCa0xXSTJNVE10T0RnNVltWXhZamsxWXpjeSJ9"
