apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundary
  template:
    metadata:
      labels:
        app: boundary
    spec:
      containers:
      - name: boundary
        image: hashicorp/boundary:latest  # Replace with the latest stable version
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
        env:
        - name: BOUNDARY_POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: boundary-db-secret
              key: db-url
        ports:
        - containerPort: 9200
        - containerPort: 9201
        - containerPort: 9202
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: ca-cert
          mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
      volumes:
      - name: ca-cert
        configMap:
          name: boundary-ca-cert