apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundary
  template:
    metadata:
      labels:
        app: boundary
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: boundary
        image: hashicorp/boundary:0.12.0  # Replace with the latest stable version
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: BOUNDARY_POSTGRES_URL
          valueFrom:
            secretKeyRef:
              name: boundary-db-secret
              key: db-url
        ports:
        - containerPort: 9200
        - containerPort: 9201
        - containerPort: 9202
